#!/usr/bin/env bash
# glue-lake-formation quickstart: bootstrap a Lake-Formation-governed Glue
# database + S3 bucket with CDK, show that SQE is DENIED until an explicit LF
# grant, grant it, show the same statement succeed, then tear everything down.
#
#   ./run.sh             # deploy -> denied -> grant -> succeeds -> destroy
#   ./run.sh --keep      # same, but leave SQE up and the stack deployed
#   ./run.sh --destroy   # just tear down (compose down + drop table + cdk destroy)
#   ./run.sh --check     # same as default, plus assert the deny/grant invariants before teardown
#
# Prereqs: Docker, Node + npx, AWS CLI v2, and AWS credentials for the target
# account (set AWS_PROFILE, or have AWS_* env vars). The caller must be a Lake
# Formation data-lake admin (so it can grant). The account must be
# cdk-bootstrapped once (`cdk bootstrap`).
#
# What this does and does not show: LF governs the Glue *catalog* operations
# SQE calls (CreateTable/GetTable). SQE reads S3 data directly with the caller's
# IAM credentials, so it does NOT enforce LF column-masking / row-filtering --
# that is SQE's own OPA/Cedar policy engine, a different mechanism. See README.
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

DB="sqe_lf_quickstart"
KEEP=0; DESTROY_ONLY=0; CHECK=0
for a in "$@"; do
  case "$a" in
    --keep) KEEP=1 ;;
    --destroy) DESTROY_ONLY=1 ;;
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --keep, --destroy, or --check)" ;;
  esac
done

require docker aws npx
[ -f .env ] || { [ -f .env.example ] && cp .env.example .env; }
# shellcheck disable=SC1091
[ -f .env ] && { set -a; . ./.env; set +a; }

step "resolving AWS credentials (profile: ${AWS_PROFILE:-default})"
eval "$(aws configure export-credentials --format env 2>/dev/null)" \
  || die "could not resolve AWS credentials. Set AWS_PROFILE or AWS_* env vars."
export AWS_REGION="${AWS_REGION:-$(aws configure get region 2>/dev/null || echo eu-example-1)}"
export CDK_DEFAULT_REGION="$AWS_REGION"
CDK_DEFAULT_ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
export CDK_DEFAULT_ACCOUNT
CALLER_ARN="$(aws sts get-caller-identity --query Arn --output text)"
ok "account $CDK_DEFAULT_ACCOUNT, region $AWS_REGION, principal $CALLER_ARN"

# Run sqe-cli against the running coordinator. Echoes the SQL result or the error.
run_sql() {
  docker compose exec -T -e SQE_PASSWORD=anonymous sqe \
    sqe-cli --port 50051 --user anonymous --file /queries.sql --stop-on-error 2>&1
}

revoke_lf() {
  aws lakeformation revoke-permissions \
    --principal "DataLakePrincipalIdentifier=$CALLER_ARN" \
    --resource "{\"Database\":{\"Name\":\"$DB\"}}" \
    --permissions CREATE_TABLE ALTER DROP DESCRIBE \
    --region "$AWS_REGION" >/dev/null 2>&1 || true
}

destroy() {
  step "tearing down"
  docker compose down -v 2>/dev/null || true
  # Drop the SQE-created table so CloudFormation can delete the database.
  aws glue delete-table --database-name "$DB" --name events --region "$AWS_REGION" 2>/dev/null \
    && ok "dropped table $DB.events" || true
  revoke_lf
  ( cd cdk && [ -d node_modules ] && npx cdk destroy --force 2>&1 | tail -3 ) \
    || warn "cdk destroy: check the stack manually"
  rm -f sqe.toml.local cdk-outputs.json
  ok "torn down"
}
if [ "$DESTROY_ONLY" -eq 1 ]; then destroy; exit 0; fi

step "cdk deploy (S3 bucket + LF-governed Glue database $DB)"
( cd cdk && { [ -d node_modules ] || npm install --silent; } \
  && npx cdk deploy --require-approval never --outputs-file ../cdk-outputs.json 2>&1 | tail -5 )
WAREHOUSE=$(python3 -c "import json;print(json.load(open('cdk-outputs.json'))['SqeGlueLfQuickstart']['WarehouseUri'])")
ok "warehouse=$WAREHOUSE  database=$DB (created by CloudFormation -> LF-governed, no grants)"

step "generating sqe.toml.local"
sed -e "s#__WAREHOUSE__#$WAREHOUSE#g" -e "s#__REGION__#$AWS_REGION#g" sqe.toml > sqe.toml.local

step "starting SQE (glue backend)"
docker compose up -d --wait
ok "sqe healthy"

OUT=OUTPUT.md
PHASE_A="$(run_sql || true)"
echo "── Phase A (no LF grant) ──"; echo "$PHASE_A"

step "granting Lake Formation permissions to $CALLER_ARN on $DB"
aws lakeformation grant-permissions \
  --principal "DataLakePrincipalIdentifier=$CALLER_ARN" \
  --resource "{\"Database\":{\"Name\":\"$DB\"}}" \
  --permissions CREATE_TABLE ALTER DROP DESCRIBE \
  --region "$AWS_REGION" >/dev/null
ok "granted CREATE_TABLE, ALTER, DROP, DESCRIBE"

# Restart SQE so it picks up the new permissions with no stale catalog state.
step "restarting SQE to clear catalog state"
docker compose up -d --force-recreate --wait sqe
ok "sqe healthy"

PHASE_B="$(run_sql || true)"
echo "── Phase B (after LF grant) ──"; echo "$PHASE_B"

step "capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ) against AWS Glue + Lake Formation._"
  echo
  echo "Principal: \`$CALLER_ARN\`. Database \`$DB\` created by CloudFormation, so"
  echo "Lake Formation governs it with no grants until we add one."
  echo
  echo '## Phase A -- before the LF grant: Lake Formation denies CREATE TABLE'
  echo '```'
  echo "$PHASE_A"
  echo '```'
  echo
  echo '## The grant'
  echo '```'
  echo "aws lakeformation grant-permissions \\"
  echo "  --principal DataLakePrincipalIdentifier=$CALLER_ARN \\"
  echo "  --resource '{\"Database\":{\"Name\":\"$DB\"}}' \\"
  echo "  --permissions CREATE_TABLE ALTER DROP DESCRIBE"
  echo '```'
  echo
  echo '## Phase B -- after the LF grant: the same statements succeed'
  echo '```'
  echo "$PHASE_B"
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

if [ "$KEEP" -eq 1 ]; then
  echo; ok "left running (--keep). Flight grpc://localhost:${SQE_FLIGHT_PORT:-60051}."
  echo "    Tear down with: ./run.sh --destroy"
  exit 0
fi

if [ "$CHECK" -eq 1 ]; then
  step "checking invariants (reusing the captured Phase A / Phase B output)"
  # The point of this scenario is the deny-then-grant flip, so assert it both
  # ways from the two captured phases (no re-run: the grant is already applied,
  # so a re-run could not reproduce the pre-grant denial).
  #
  # Phase A (before the grant): Lake Formation denies CREATE TABLE. OUTPUT.md
  # shows the LF-specific message, which is more precise than bare AccessDenied.
  assert_contains     "Phase A: Lake Formation denies CREATE TABLE" "$PHASE_A" "Insufficient Lake Formation permission"
  assert_contains     "Phase A: error names Create Table"           "$PHASE_A" "Required Create Table on $DB"
  # Phase B (after the grant): the same statements succeed and the aggregate
  # comes back (purchase -> 55.25, click -> 2.25) with no engine error. Do NOT
  # assert_not_contains 'error' on Phase A -- that phase is an error by design.
  assert_contains     "Phase B: aggregate shows purchase total"     "$PHASE_B" "55.25"
  assert_contains     "Phase B: aggregate shows click total"        "$PHASE_B" "2.25"
  assert_not_contains "Phase B: run has no error after the grant"   "$PHASE_B" "error"
  # Tear down before check_summary: check_summary dies on a failed assertion, so
  # summarizing first would leak the deployed bucket + LF-governed database.
  destroy
  check_summary
  exit 0
fi
destroy
