#!/usr/bin/env bash
# Quack quickstart: bring SQE up with the DuckDB Quack RPC endpoint enabled and
# prove the server speaks Quack (the `GET /` identification probe). Quack is a
# pre-release DuckDB protocol; a full client round-trip needs a quack-capable
# DuckDB build, so this run.sh validates the SERVER side and the README documents
# how a client attaches. See the README "Status" section.
#
#   ./run.sh             # up -> GET / identification probe -> capture
#   ./run.sh --down      # tear everything down
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

for a in "$@"; do
  case "$a" in
    --down) require docker; step "tearing down"; docker compose down -v; ok "done"; exit 0 ;;
    *) die "unknown arg: $a (use --down)" ;;
  esac
done

require docker curl
[ -f .env ] || { [ -f .env.example ] && cp .env.example .env; }
# shellcheck disable=SC1091
[ -f .env ] && { set -a; . ./.env; set +a; }
QUACK="http://localhost:${SQE_QUACK_PORT:-19494}"

step "bringing the stack up (rustfs, nessie, sqe with quack_port=9494)"
docker compose up -d --wait
ok "all services up"

step "probing the Quack endpoint: GET / (identification)"
IDENT="$(curl -fsS -m 5 "$QUACK/" || true)"
[ -n "$IDENT" ] || die "GET $QUACK/ returned nothing -- is the Quack port exposed?"
echo "$IDENT"
ok "the server identifies as a DuckDB Quack endpoint"

OUT=OUTPUT.md
step "capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## The Quack endpoint identifies itself (`GET /`)'
  echo '```'
  echo "\$ curl ${QUACK}/"
  echo "$IDENT"
  echo '```'
  echo
  echo '## SQE logs on startup (Quack enabled, with its security warnings)'
  echo '```'
  docker compose logs sqe 2>&1 | grep -iE 'Quack' | sed -E 's/.*"message":"([^"]*)".*/\1/' | head -5
  echo '```'
  echo
  echo "A full client round-trip (a DuckDB client running queries) needs a"
  echo "quack-capable DuckDB build; see the README. The server side is what this"
  echo "run validates: the endpoint is up and speaks Quack."
} | tee "$OUT"
ok "captured to $OUT"
echo
ok "done. Quack endpoint: $QUACK   Tear down: ./run.sh --down"
