#!/usr/bin/env bash
# Quack quickstart: bring SQE up with the DuckDB Quack RPC endpoint enabled,
# prove the server speaks Quack (the `GET /` probe), then -- if a quack-capable
# DuckDB CLI is on PATH -- run a real client round-trip: a DuckDB client queries
# an Iceberg table through SQE over the Quack protocol.
#
#   ./run.sh             # up -> GET / probe -> (DuckDB round-trip if available) -> capture
#   ./run.sh --down      # tear everything down
#   ./run.sh --check     # up -> probe -> (round-trip) -> assert key invariants
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

CHECK=0
for a in "$@"; do
  case "$a" in
    --down) require docker; step "tearing down"; docker compose down -v; ok "done"; exit 0 ;;
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --down or --check)" ;;
  esac
done

require docker curl
[ -f .env ] || { [ -f .env.example ] && cp .env.example .env; }
# shellcheck disable=SC1091
[ -f .env ] && { set -a; . ./.env; set +a; }
QUACK_PORT="${SQE_QUACK_PORT:-19494}"
QUACK="http://localhost:${QUACK_PORT}"

step "bringing the stack up (rustfs, nessie, sqe with quack_port=9494)"
docker compose up -d --wait
ok "all services up"

step "probing the Quack endpoint: GET / (identification)"
IDENT="$(curl -fsS -m 5 "$QUACK/" || true)"
[ -n "$IDENT" ] || die "GET $QUACK/ returned nothing -- is the Quack port exposed?"
echo "$IDENT"
ok "the server identifies as a DuckDB Quack endpoint"

sqe_exec() { docker compose exec -T -e SQE_PASSWORD=anonymous sqe \
  sqe-cli --port 50051 --user anonymous --stop-on-error -e "$1" >/dev/null 2>&1; }

# Real client round-trip, when a quack-capable DuckDB CLI is available. The Quack
# protocol + its DuckDB extension are pre-release: this needs duckdb 1.5.3+ and
# `INSTALL quack FROM core_nightly` (which fetches the extension over the net).
ROUNDTRIP=""
if command -v duckdb >/dev/null 2>&1; then
  step "DuckDB client round-trip (duckdb $(duckdb --version | awk '{print $1}'))"
  step "  seeding an Iceberg table in SQE (nessie.demo.events)"
  sqe_exec "CREATE SCHEMA IF NOT EXISTS nessie.demo"
  sqe_exec "CREATE TABLE IF NOT EXISTS nessie.demo.events (id BIGINT, kind VARCHAR, amount DOUBLE)"
  sqe_exec "INSERT INTO nessie.demo.events VALUES (1,'click',1.5),(2,'purchase',42.0),(3,'click',0.75),(4,'purchase',13.25)"
  # The anonymous provider accepts any non-empty token; CREATE SECRET supplies it.
  ROUNDTRIP="$(duckdb -c "
    INSTALL quack FROM core_nightly; LOAD quack;
    CREATE SECRET (TYPE quack, TOKEN 'anonymous');
    SELECT kind, COUNT(*) AS n, ROUND(SUM(amount),2) AS total
    FROM quack_query('quack:localhost:${QUACK_PORT}', 'SELECT kind, amount FROM nessie.demo.events')
    GROUP BY kind ORDER BY total DESC;
  " 2>&1 || true)"
  echo "$ROUNDTRIP"
  ok "DuckDB queried an SQE Iceberg table over Quack"
else
  warn "duckdb not on PATH -- skipping the client round-trip (server probe still passed)."
  echo "    Install duckdb 1.5.3+ and re-run to see a DuckDB client query SQE over Quack."
fi

OUT=OUTPUT.md
step "capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## The Quack endpoint identifies itself (`GET /`)'
  echo '```'
  echo "\$ curl ${QUACK}/"
  echo "$IDENT"
  echo '```'
  echo
  if [ -n "$ROUNDTRIP" ]; then
    echo '## A DuckDB CLI queries an SQE Iceberg table over Quack'
    echo
    echo 'DuckDB connects to `quack:localhost:'"${QUACK_PORT}"'`, runs `quack_query()` against'
    echo 'SQE (which reads the table from the Nessie catalog + S3), and aggregates the result:'
    echo '```'
    echo "$ROUNDTRIP"
    echo '```'
    echo
  fi
  echo '## SQE logs on startup (Quack enabled, with its security warnings)'
  echo '```'
  docker compose logs sqe 2>&1 | grep -iE 'Quack' | sed -E 's/.*"message":"([^"]*)".*/\1/' | head -5
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

if [ "$CHECK" -eq 1 ]; then
  step "checking invariants (reusing the GET / probe and the round-trip result)"

  # The server identification is always available once the stack is up.
  assert_contains "Quack endpoint identifies itself" "$IDENT" "DuckDB Quack RPC endpoint"

  # The DuckDB client round-trip only ran if a quack-capable duckdb CLI was on
  # PATH (and the nightly extension fetch succeeded). Assert on its result only
  # when present, so a missing/unavailable duckdb does not false-fail.
  if [ -n "$ROUNDTRIP" ]; then
    assert_contains "DuckDB round-trip reads the purchase total" "$ROUNDTRIP" "55.25"
  else
    warn "duckdb round-trip skipped (no quack-capable duckdb CLI) -- probe-only check"
  fi

  check_summary
  exit 0
fi

echo
ok "done. Quack endpoint: $QUACK   Tear down: ./run.sh --down"
