#!/usr/bin/env bash
# AWS Glue quickstart: bootstrap throwaway Glue + S3 resources with CDK, run a
# create/write/read round-trip through SQE's glue backend, capture the output,
# then tear the resources back down.
#
#   ./run.sh             # cdk deploy -> up -> queries -> down -> cdk destroy
#   ./run.sh --keep      # same, but leave SQE up and the CDK stack deployed
#   ./run.sh --destroy   # just tear down (compose down + cdk destroy)
#
# Prereqs: Docker, Node + npx, AWS CLI v2, and AWS credentials for the target
# account (set AWS_PROFILE, or have AWS_* env vars). The account must be
# cdk-bootstrapped once (`cdk bootstrap`) -- most are already.
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

KEEP=0; DESTROY_ONLY=0
for a in "$@"; do
  case "$a" in
    --keep) KEEP=1 ;;
    --destroy) DESTROY_ONLY=1 ;;
    *) die "unknown arg: $a (use --keep or --destroy)" ;;
  esac
done

require docker aws npx
[ -f .env ] || { [ -f .env.example ] && cp .env.example .env; }
# shellcheck disable=SC1091
[ -f .env ] && { set -a; . ./.env; set +a; }

# Resolve credentials for the active profile into env (works for static keys,
# SSO, and assumed roles) so both the CDK CLI and the SQE container get them.
step "resolving AWS credentials (profile: ${AWS_PROFILE:-default})"
eval "$(aws configure export-credentials --format env 2>/dev/null)" \
  || die "could not resolve AWS credentials. Set AWS_PROFILE or AWS_* env vars."
export AWS_REGION="${AWS_REGION:-$(aws configure get region 2>/dev/null || echo eu-example-1)}"
export CDK_DEFAULT_REGION="$AWS_REGION"
export CDK_DEFAULT_ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
ok "account $CDK_DEFAULT_ACCOUNT, region $AWS_REGION"

destroy() {
  step "tearing down"
  docker compose down -v 2>/dev/null || true
  # SQE created the Glue database (not the CDK), so drop it here. Iceberg tables
  # are deleted with the bucket; delete-database removes the catalog entry.
  aws glue delete-database --name sqe_glue_quickstart --region "${AWS_REGION:-eu-example-1}" 2>/dev/null \
    && ok "dropped glue database sqe_glue_quickstart" || true
  ( cd cdk && [ -d node_modules ] && npx cdk destroy --force 2>&1 | tail -3 ) || warn "cdk destroy: check the stack manually"
  rm -f sqe.toml.local cdk-outputs.json
  ok "torn down"
}
if [ "$DESTROY_ONLY" -eq 1 ]; then destroy; exit 0; fi

step "cdk deploy (Glue database + S3 warehouse bucket)"
( cd cdk && { [ -d node_modules ] || npm install --silent; } \
  && npx cdk deploy --require-approval never --outputs-file ../cdk-outputs.json 2>&1 | tail -5 )

WAREHOUSE=$(python3 -c "import json;print(json.load(open('cdk-outputs.json'))['SqeGlueQuickstart']['WarehouseUri'])")
ok "warehouse=$WAREHOUSE  (SQE creates the glue database sqe_glue_quickstart itself)"

step "generating sqe.toml.local from sqe.toml"
sed -e "s#__WAREHOUSE__#$WAREHOUSE#g" -e "s#__REGION__#$AWS_REGION#g" sqe.toml > sqe.toml.local

step "starting SQE (glue backend)"
docker compose up -d --wait
ok "sqe healthy"

OUT=OUTPUT.md
step "running create/write/read round-trip, capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ) against AWS Glue._"
  echo
  echo '## anonymous user, glue backend: CREATE TABLE + INSERT + aggregate'
  echo
  echo '`sqe-cli --user anonymous --file queries.sql` over Flight SQL:'
  echo '```'
  docker compose exec -T -e SQE_PASSWORD=anonymous sqe \
    sqe-cli --port 50051 --user anonymous --file /queries.sql --stop-on-error 2>&1
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

if [ "$KEEP" -eq 1 ]; then
  echo; ok "left running (--keep). Flight grpc://localhost:${SQE_FLIGHT_PORT:-60051}."
  echo "    Tear down with: ./run.sh --destroy"
  exit 0
fi
destroy
