[package]
name = "sqe-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "Apache-2.0"
repository.workspace = true

[dependencies]
sqe-core = { path = "../sqe-core" }
sqlparser = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
proptest = "1"
