#!/usr/bin/env bash
# Persistent local Iceberg catalog with SQE's embedded engine, no server.
# `sqe-cli --embedded --warehouse <dir>` attaches a SQLite-backed Iceberg
# catalog at <dir>. This runs TWO separate processes against the same warehouse
# to prove the catalog + data persist on disk between invocations.
#
#   ./run.sh            # create+write (process 1), then reopen+read (process 2)
#   ./run.sh --clean    # delete the local ./warehouse first, then run
#   ./run.sh --check    # run, then assert the persisted read returns the rows
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

CHECK=0
for a in "$@"; do
  case "$a" in
    --clean) rm -rf warehouse ;;
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --clean or --check)" ;;
  esac
done

require docker
IMG="${SQE_IMAGE:-sqe-quickstart:latest}"
docker image inspect "$IMG" >/dev/null 2>&1 || die "image $IMG not found. Build it: (cd ../polaris-keycloak-client-id && docker compose build sqe) or set SQE_IMAGE."

mkdir -p warehouse
WH="$PWD/warehouse"

OUT=OUTPUT.md
step "process 1: create + write; process 2: reopen + read (capturing to $OUT)"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## Process 1 -- create schema + table + insert (writes to the SQLite catalog)'
  echo '```'
  echo "\$ sqe-cli --embedded --warehouse ./warehouse --file queries-init.sql"
  docker run --rm --entrypoint sqe-cli \
    -v "$WH":/data/wh -v "$PWD/queries-init.sql":/init.sql:ro \
    "$IMG" --embedded --warehouse /data/wh --file /init.sql --stop-on-error 2>&1
  echo '```'
  echo
  echo '## Process 2 -- a *separate* invocation reopens the same warehouse and reads'
  echo '```'
  echo "\$ sqe-cli --embedded --warehouse ./warehouse -e \"SELECT ... FROM iceberg.demo.events\""
  docker run --rm --entrypoint sqe-cli -v "$WH":/data/wh \
    "$IMG" --embedded --warehouse /data/wh \
    -e "SELECT kind, COUNT(*) AS n, ROUND(SUM(amount),2) AS total FROM iceberg.demo.events GROUP BY kind ORDER BY total DESC" 2>&1
  echo '```'
  echo
  echo '## On disk: the SQLite catalog (sqe.db) + Iceberg metadata/data'
  echo '```'
  ls -1 warehouse 2>&1
  echo '```'
} | tee "$OUT"
ok "captured to $OUT. The catalog persists in ./warehouse; re-run to query again, or ./run.sh --clean to reset."

if [ "$CHECK" -eq 1 ]; then
  step "checking invariants (a separate process reopens the persisted warehouse)"

  # Process 2: a fresh embedded invocation reopens the same SQLite-backed
  # warehouse and reads back what process 1 wrote. Bare SELECT aggregate, so
  # assert on the persisted purchase total from OUTPUT.md.
  read_out=$(docker run --rm --entrypoint sqe-cli -v "$WH":/data/wh \
    "$IMG" --embedded --warehouse /data/wh \
    -e "SELECT kind, COUNT(*) AS n, ROUND(SUM(amount),2) AS total FROM iceberg.demo.events GROUP BY kind ORDER BY total DESC" 2>&1)
  assert_not_empty   "persisted read returns rows"        "$read_out"
  assert_contains    "persisted read shows purchase total" "$read_out" "55.25"
  assert_not_contains "persisted read has no error"        "$read_out" "error"

  check_summary
  exit 0
fi
