#!/usr/bin/env bash
# Attach multiple persistent Iceberg catalogs in one embedded session and query
# across them. `sqe-cli --embedded --catalog NAME=PATH` (repeatable) mounts each
# catalog under its own SQLite-backed warehouse; a single query can JOIN tables
# from different catalogs. No server.
#
#   ./run.sh            # seed two catalogs, then attach both + cross-catalog JOIN
#   ./run.sh --clean    # reset ./catalogs first
#   ./run.sh --check    # run, then assert the cross-catalog JOIN returns rows
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

CHECK=0
for a in "$@"; do
  case "$a" in
    --clean) rm -rf catalogs ;;
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --clean or --check)" ;;
  esac
done

require docker
IMG="${SQE_IMAGE:-sqe-quickstart:latest}"
docker image inspect "$IMG" >/dev/null 2>&1 || die "image $IMG not found. Build it: (cd ../polaris-keycloak-client-id && docker compose build sqe) or set SQE_IMAGE."

# --check must be re-runnable, so it always starts from clean catalogs.
# Interactive ./run.sh keeps the persisted catalogs; use --clean to reset.
[ "${CHECK:-0}" = 1 ] && rm -rf catalogs
mkdir -p catalogs/sales catalogs/ref
S="$PWD/catalogs/sales" R="$PWD/catalogs/ref"

OUT=OUTPUT.md
step "seeding two catalogs, then attaching both for a cross-catalog JOIN (-> $OUT)"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## Seed the `sales` and `ref` catalogs (separate warehouses)'
  echo '```'
  echo "\$ sqe-cli --embedded --catalog sales=./catalogs/sales --file seed-sales.sql"
  docker run --rm --entrypoint sqe-cli -v "$S":/d/sales -v "$PWD/seed-sales.sql":/s.sql:ro \
    "$IMG" --embedded --catalog sales=/d/sales --file /s.sql --stop-on-error 2>&1
  echo "\$ sqe-cli --embedded --catalog ref=./catalogs/ref --file seed-ref.sql"
  docker run --rm --entrypoint sqe-cli -v "$R":/d/ref -v "$PWD/seed-ref.sql":/r.sql:ro \
    "$IMG" --embedded --catalog ref=/d/ref --file /r.sql --stop-on-error 2>&1
  echo '```'
  echo
  echo '## Attach BOTH catalogs and JOIN across them in one query'
  echo '```'
  echo "\$ sqe-cli --embedded --catalog sales=... --catalog ref=... -e \"... JOIN ...\""
  docker run --rm --entrypoint sqe-cli -v "$S":/d/sales -v "$R":/d/ref \
    "$IMG" --embedded --catalog sales=/d/sales --catalog ref=/d/ref \
    -e "SELECT r.name, COUNT(*) AS n, ROUND(SUM(o.amount),2) AS total \
        FROM sales.public.orders o JOIN ref.public.regions r ON o.region_id = r.region_id \
        GROUP BY r.name ORDER BY total DESC" 2>&1
  echo '```'
} | tee "$OUT"
ok "captured to $OUT. Both catalogs persist under ./catalogs; ./run.sh --clean to reset."

if [ "$CHECK" -eq 1 ]; then
  step "checking invariants (re-running the cross-catalog JOIN over both warehouses)"

  # Attach both warehouses and JOIN sales.orders against ref.regions. Bare SELECT
  # aggregate, so assert on the region name and total from OUTPUT.md.
  join_out=$(docker run --rm --entrypoint sqe-cli -v "$S":/d/sales -v "$R":/d/ref \
    "$IMG" --embedded --catalog sales=/d/sales --catalog ref=/d/ref \
    -e "SELECT r.name, COUNT(*) AS n, ROUND(SUM(o.amount),2) AS total \
        FROM sales.public.orders o JOIN ref.public.regions r ON o.region_id = r.region_id \
        GROUP BY r.name ORDER BY total DESC" 2>&1)
  assert_not_empty   "cross-catalog JOIN returns rows"   "$join_out"
  assert_contains    "JOIN resolves the EU region"       "$join_out" "EU"
  assert_contains    "JOIN sums the EU total"            "$join_out" "49.25"
  assert_not_contains "JOIN has no error"                "$join_out" "error"

  check_summary
  exit 0
fi
