#!/usr/bin/env bash
# Distributed SQE: a coordinator + two workers over Arrow Flight, against the
# shared Polaris + RustFS test stack. Brings the stack up, bootstraps Polaris,
# runs the end-to-end distributed assertions (connectivity, system tables,
# query history, CTAS round-trip, result cache, worker dispatch, Trino HTTP),
# and captures the output.
#
#   ./run.sh             # up -> bootstrap -> queries -> capture
#   ./run.sh --down      # tear the whole stack down
#   ./run.sh --check     # up -> bootstrap -> assert the distributed invariants
#
# The distributed stack is heavy (it builds the SQE image and runs four
# containers plus Polaris/RustFS), so it is deliberately NOT part of the
# self-contained `scripts/test.sh scenario all` set. Run it explicitly with
# `scripts/test.sh scenario distributed`.
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

# Resolve the repo root so we can reach the root-level compose files and the
# native CLI binary regardless of the caller's working directory (scripts/
# test.sh cd's into this directory before invoking us).
ROOT_DIR="$(cd ../.. && pwd)"

# The distributed compose file is an OVERLAY: it adds coordinator + workers but
# inherits Polaris, RustFS, and Postgres from docker-compose.test.yml. Both -f
# flags are required or the coordinator comes up with no catalog behind it.
COMPOSE=(-f "$ROOT_DIR/docker-compose.test.yml" -f "$ROOT_DIR/docker-compose.distributed.yml")

CHECK=0
for a in "$@"; do
  case "$a" in
    --down) require docker; step "tearing down"; docker compose "${COMPOSE[@]}" down -v; ok "done"; exit 0 ;;
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --down or --check)" ;;
  esac
done

require docker curl python3 cargo

SQE_HOST="localhost"
SQE_PORT="60051"
TRINO_PORT="28080"
SQE_USER="${SQE_USER:-root}"
export SQE_PASSWORD="${SQE_PASSWORD:-}"

# ── Build the native CLI used to drive the coordinator from the host ────────
step "building sqe-cli (release)"
cargo build -p sqe-cli --release
CLI="$ROOT_DIR/target/release/sqe-cli"
[ -x "$CLI" ] || die "sqe-cli not found at $CLI after build"

# cli_query <sql>: run a statement over Flight SQL against the coordinator.
cli_query() {
  "$CLI" --host "$SQE_HOST" --port "$SQE_PORT" --user "$SQE_USER" \
    --protocol flight -e "$1" 2>/dev/null
}

# trino_query <sql>: submit a statement to the coordinator's Trino HTTP port.
trino_query() {
  local creds
  creds=$(printf '%s:%s' "$SQE_USER" "$SQE_PASSWORD" | base64)
  curl -s -X POST "http://$SQE_HOST:$TRINO_PORT/v1/statement" \
    -H "Authorization: Basic $creds" \
    -H "X-Trino-User: $SQE_USER" \
    -d "$1"
}

# ── Bring the distributed stack up + bootstrap Polaris ──────────────────────
step "bringing the distributed stack up (build SQE on first run; this can take a few minutes)"
docker compose "${COMPOSE[@]}" up --build -d
ok "containers started (polaris, rustfs, coordinator, worker-1, worker-2)"

step "bootstrapping Polaris (warehouse, namespace, grants) + waiting for coordinator"
"$ROOT_DIR/scripts/bootstrap-distributed.sh"

OUT=OUTPUT.md
step "running the distributed demo queries, capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## Cluster topology (system.runtime.nodes)'
  echo '```'
  cli_query "SELECT node_id, coordinator, state FROM system.runtime.nodes" 2>&1
  echo '```'
  echo
  echo '## A CTAS round-trip and a worker-dispatched aggregate'
  echo '```'
  cli_query "CREATE SCHEMA IF NOT EXISTS test_warehouse.dist_test" >/dev/null 2>&1 || true
  cli_query "DROP TABLE IF EXISTS test_warehouse.dist_test.numbers" >/dev/null 2>&1 || true
  cli_query "CREATE TABLE test_warehouse.dist_test.numbers AS SELECT * FROM (VALUES (1, 'one'), (2, 'two'), (3, 'three')) AS t(id, name)" 2>&1
  cli_query "SELECT * FROM test_warehouse.dist_test.numbers ORDER BY id" 2>&1
  echo '```'
  echo
  echo '## Recent query history (system.runtime.queries)'
  echo '```'
  cli_query "SELECT query_id, state FROM system.runtime.queries ORDER BY created DESC LIMIT 5" 2>&1
  echo '```'
  echo
  echo '## Cleanup'
  echo '```'
  cli_query "DROP TABLE IF EXISTS test_warehouse.dist_test.numbers" >/dev/null 2>&1 || true
  echo "dropped test_warehouse.dist_test.numbers"
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

if [ "$CHECK" -eq 1 ]; then
  step "checking distributed invariants (ported 1:1 from the retired distributed-test.sh)"

  # Test 1: Basic connectivity
  out=$(cli_query "SELECT 1 AS x" || echo "CONNECT_FAIL")
  assert_contains "SELECT 1 returns result" "$out" "1"

  # Test 2: system.runtime.nodes lists the coordinator
  out=$(cli_query "SELECT node_id, coordinator, state FROM system.runtime.nodes" || echo "")
  assert_contains "coordinator node present" "$out" "coordinator"

  # Test 3: system.runtime.queries records FINISHED queries
  cli_query "SELECT 42 AS answer" >/dev/null 2>&1 || true
  sleep 1
  out=$(cli_query "SELECT query_id, state FROM system.runtime.queries ORDER BY created DESC LIMIT 5" || echo "")
  assert_contains "query history has FINISHED entries" "$out" "FINISHED"

  # Test 4: system.metadata.catalogs
  out=$(cli_query "SELECT catalog_name, connector_id FROM system.metadata.catalogs" || echo "")
  assert_contains "catalog name present" "$out" "test_warehouse"
  assert_contains "connector is iceberg" "$out" "iceberg"

  # Test 5: create table and read it back
  cli_query "CREATE SCHEMA IF NOT EXISTS test_warehouse.dist_test" >/dev/null 2>&1 || true
  cli_query "DROP TABLE IF EXISTS test_warehouse.dist_test.numbers" >/dev/null 2>&1 || true
  cli_query "CREATE TABLE test_warehouse.dist_test.numbers AS SELECT * FROM (VALUES (1, 'one'), (2, 'two'), (3, 'three')) AS t(id, name)" >/dev/null 2>&1 || true
  out=$(cli_query "SELECT * FROM test_warehouse.dist_test.numbers ORDER BY id" || echo "")
  assert_contains "table has data" "$out" "one"

  # Test 6: system.metadata.table_properties
  out=$(cli_query "SELECT property_name FROM system.metadata.table_properties WHERE table_name = 'numbers' LIMIT 5" || echo "")
  assert_not_empty "table properties returned" "$out"

  # Test 7: system.metadata.table_comments
  out=$(cli_query "SELECT table_name FROM system.metadata.table_comments WHERE schema_name = 'dist_test'" || echo "")
  assert_contains "table comment row exists" "$out" "numbers"

  # Test 8: system.runtime.tasks
  out=$(cli_query "SELECT query_id, task_id FROM system.runtime.tasks LIMIT 5" || echo "")
  assert_not_empty "tasks table has entries" "$out"

  # Test 9: query result cache (timing only -- informational, not a counted
  # assertion. The retired script PASS'd this unconditionally; we report the
  # T1 -> T2 timing instead of faking a tautological check.)
  t1_start=$(python3 -c "import time; print(int(time.time()*1000))")
  cli_query "SELECT COUNT(*) FROM test_warehouse.dist_test.numbers" >/dev/null 2>&1 || true
  t1_end=$(python3 -c "import time; print(int(time.time()*1000))")
  t2_start=$(python3 -c "import time; print(int(time.time()*1000))")
  cli_query "SELECT COUNT(*) FROM test_warehouse.dist_test.numbers" >/dev/null 2>&1 || true
  t2_end=$(python3 -c "import time; print(int(time.time()*1000))")
  ok "cache timing: $((t1_end - t1_start))ms -> $((t2_end - t2_start))ms (informational)"

  # Test 10: cache invalidation on write
  cli_query "INSERT INTO test_warehouse.dist_test.numbers VALUES (4, 'four')" >/dev/null 2>&1 || true
  out=$(cli_query "SELECT COUNT(*) AS cnt FROM test_warehouse.dist_test.numbers" || echo "")
  assert_contains "count reflects INSERT" "$out" "4"

  # Test 11: Trino HTTP endpoint
  out=$(trino_query "SELECT 1 AS x" || echo "")
  assert_not_empty "Trino endpoint returns response" "$out"

  # Test 12: information_schema
  out=$(cli_query "SELECT table_name FROM information_schema.tables WHERE table_schema = 'dist_test'" || echo "")
  assert_contains "information_schema shows table" "$out" "numbers"

  # Test 13: distributed execution actually reaches a worker. Force enough data
  # files that the planner MUST dispatch, then sample system.runtime.tasks.
  for i in 5 6 7 8; do
    cli_query "INSERT INTO test_warehouse.dist_test.numbers VALUES ($i, 'row_$i')" >/dev/null 2>&1 || true
  done
  cli_query "SELECT id, COUNT(*) FROM test_warehouse.dist_test.numbers GROUP BY id" >/dev/null 2>&1 || true
  sleep 1
  out=$(cli_query "SELECT task_id, node_id FROM system.runtime.tasks ORDER BY query_id DESC LIMIT 20" || echo "")
  assert_contains "tasks distributed to workers" "$out" "worker"

  # Test 14: tasks table carries state + timing
  out=$(cli_query "SELECT task_id, node_id, state, elapsed_ms FROM system.runtime.tasks LIMIT 3" || echo "")
  assert_not_empty "tasks have state and timing" "$out"

  # Cleanup
  cli_query "DROP TABLE IF EXISTS test_warehouse.dist_test.numbers" >/dev/null 2>&1 || true

  check_summary
  exit 0
fi

echo
ok "done. Flight grpc://localhost:${SQE_PORT}, Trino http://localhost:${TRINO_PORT}/v1/info. Tear down: ./run.sh --down"
