#!/usr/bin/env bash
# Set up the stack, mint a Keycloak token for a user, query SQE with that token
# (--token), and capture the output. Demonstrates bring-your-own-token auth.
#
#   ./run.sh             # up -> bootstrap -> mint token -> query -> capture
#   ./run.sh --down      # tear everything down
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

for a in "$@"; do
  case "$a" in
    --down) require docker; step "tearing down"; docker compose down -v; ok "done"; exit 0 ;;
    *) die "unknown arg: $a (use --down)" ;;
  esac
done

require docker curl
[ -f .env ] || { step "creating .env from .env.example"; cp .env.example .env; }
# shellcheck disable=SC1091
set -a; . ./.env; set +a
KC="http://localhost:${KEYCLOAK_PORT:-28080}"

step "bringing the stack up (build SQE on first run; this can take a few minutes)"
docker compose up -d --wait
ok "all services healthy and bootstrap completed"

# Mint a user token from Keycloak's PUBLIC client (no client secret). This stands
# in for an upstream app / IdP that already authenticated the user.
mint() {
  curl -s -X POST "$KC/realms/iceberg/protocol/openid-connect/token" \
    -d "grant_type=password&client_id=polaris-frontend-client&username=$1&password=$2&scope=openid" \
    | sed -n 's/.*"access_token":"\([^"]*\)".*/\1/p'
}

step "minting Keycloak tokens (public client polaris-frontend-client)"
ADMTOK=$(mint adminuser adminuser123); [ -n "$ADMTOK" ] || die "could not mint adminuser token"
TESTTOK=$(mint testuser testuser123);  [ -n "$TESTTOK" ] || die "could not mint testuser token"
ok "minted adminuser + testuser tokens"

OUT=OUTPUT.md
step "querying SQE with --token, capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## adminuser, authenticated by a pre-minted Keycloak token (`--token`)'
  echo
  echo '`sqe-cli --token <jwt> --file queries.sql` over Flight SQL:'
  echo '```'
  docker compose exec -T sqe sqe-cli --port 50051 --token "$ADMTOK" --file /queries.sql --stop-on-error 2>&1
  echo '```'
  echo
  echo '## testuser token (table_reader): read works, write is denied by Polaris RBAC'
  echo '```'
  echo '$ sqe-cli --token <testuser-jwt> -e "SELECT COUNT(*) FROM quickstart.demo.events"'
  docker compose exec -T sqe sqe-cli --port 50051 --token "$TESTTOK" \
    -e "SELECT COUNT(*) AS rows FROM quickstart.demo.events" 2>&1
  echo
  echo '$ sqe-cli --token <testuser-jwt> -e "INSERT ..."   # expect 403'
  docker compose exec -T sqe sqe-cli --port 50051 --token "$TESTTOK" \
    -e "INSERT INTO quickstart.demo.events VALUES (99,'x',0.0)" 2>&1 | head -3 || true
  echo '```'
  echo
  echo '## an invalid token is rejected by SQE before any query runs'
  echo '```'
  echo '$ sqe-cli --token not.a.real.jwt -e "SELECT 1"'
  docker compose exec -T sqe sqe-cli --port 50051 --token "not.a.real.jwt" \
    -e "SELECT 1" 2>&1 | head -3 || true
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

echo
ok "done. Flight grpc://localhost:${SQE_FLIGHT_PORT:-60051}, Keycloak $KC. Tear down: ./run.sh --down"
