#!/usr/bin/env bash
# Query local and remote files with SQE's embedded engine. No server, no
# catalog, no compose: sqe-cli --embedded runs the engine in-process and the
# read_csv / read_json / read_parquet TVFs read files directly.
#
# Uses the SQE container image so you need nothing but Docker. If you have the
# CLI built locally, the same commands work with `sqe-cli` instead of the
# docker run wrapper.
#
#   ./run.sh           # run queries, capture to OUTPUT.md
#   ./run.sh --check   # run queries, then assert the key invariants
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

CHECK=0
for a in "$@"; do
  case "$a" in
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --check)" ;;
  esac
done

require docker
IMG="${SQE_IMAGE:-sqe-quickstart:latest}"
docker image inspect "$IMG" >/dev/null 2>&1 || die "image $IMG not found. Build it: (cd ../polaris-keycloak-client-id && docker compose build sqe) or set SQE_IMAGE."

# sqe() — run the embedded CLI in the image with ./data mounted read-only.
sqe() { docker run --rm --entrypoint sqe-cli -v "$PWD/data":/data:ro "$IMG" --embedded --memory "$@"; }

REMOTE="https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/parquet/userdata1.parquet"

OUT=OUTPUT.md
step "querying local + remote files with the embedded engine, capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## Local CSV (read_csv)'
  echo '```'
  echo "\$ sqe-cli --embedded --memory -e \"... read_csv('data/events.csv') ...\""
  sqe -e "SELECT kind, COUNT(*) AS n, ROUND(SUM(amount),2) AS total FROM read_csv('/data/events.csv') GROUP BY kind ORDER BY total DESC" 2>&1
  echo '```'
  echo
  echo '## Local JSON (read_json) and Parquet (read_parquet)'
  echo '```'
  echo "\$ ... read_json('data/events.json')"
  sqe -e "SELECT COUNT(*) AS rows, ROUND(SUM(amount),2) AS total FROM read_json('/data/events.json')" 2>&1
  echo "\$ ... read_parquet('data/events.parquet')"
  sqe -e "SELECT kind, ROUND(SUM(amount),2) AS total FROM read_parquet('/data/events.parquet') GROUP BY kind ORDER BY kind" 2>&1
  echo '```'
  echo
  echo '## Join two files of different formats in one query'
  echo '```'
  sqe -e "SELECT c.id, c.kind FROM read_csv('/data/events.csv') c JOIN read_parquet('/data/events.parquet') p ON c.id = p.id WHERE c.amount > 10 ORDER BY c.id" 2>&1
  echo '```'
  echo
  echo '## Remote file over HTTPS (read_parquet on a URL)'
  echo '```'
  echo "\$ ... read_parquet('$REMOTE')"
  sqe -e "SELECT COUNT(*) AS rows FROM read_parquet('$REMOTE')" 2>&1
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

if [ "$CHECK" -eq 1 ]; then
  step "checking invariants (reusing the embedded sqe() runner)"

  # Local Parquet read returns the three event kinds with the totals from
  # OUTPUT.md (click 2.25, purchase 55.25, refund -5.0) and no engine error.
  parquet_out=$(sqe -e "SELECT kind, ROUND(SUM(amount),2) AS total FROM read_parquet('/data/events.parquet') GROUP BY kind ORDER BY kind" 2>&1)
  assert_not_empty   "read_parquet returns rows"            "$parquet_out"
  assert_not_contains "read_parquet has no error"           "$parquet_out" "error"
  assert_contains    "read_parquet shows purchase total"    "$parquet_out" "55.25"

  # Remote Parquet over HTTPS returns the expected 1000-row count.
  remote_out=$(sqe -e "SELECT COUNT(*) AS rows FROM read_parquet('$REMOTE')" 2>&1)
  assert_not_contains "remote read_parquet has no error"    "$remote_out" "error"
  assert_contains    "remote read_parquet returns 1000 rows" "$remote_out" "1000"

  check_summary
  exit 0
fi

echo
ok "done. Embedded mode leaves nothing behind (ephemeral --memory engine)."
