#!/usr/bin/env bash
# Query local and remote files with SQE's embedded engine. No server, no
# catalog, no compose: sqe-cli --embedded runs the engine in-process and the
# read_csv / read_json / read_parquet TVFs read files directly.
#
# Uses the SQE container image so you need nothing but Docker. If you have the
# CLI built locally, the same commands work with `sqe-cli` instead of the
# docker run wrapper.
#
#   ./run.sh
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

require docker
IMG="${SQE_IMAGE:-sqe-quickstart:latest}"
docker image inspect "$IMG" >/dev/null 2>&1 || die "image $IMG not found. Build it: (cd ../polaris-keycloak-client-id && docker compose build sqe) or set SQE_IMAGE."

# sqe() — run the embedded CLI in the image with ./data mounted read-only.
sqe() { docker run --rm --entrypoint sqe-cli -v "$PWD/data":/data:ro "$IMG" --embedded --memory "$@"; }

REMOTE="https://raw.githubusercontent.com/Teradata/kylo/master/samples/sample-data/parquet/userdata1.parquet"

OUT=OUTPUT.md
step "querying local + remote files with the embedded engine, capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## Local CSV (read_csv)'
  echo '```'
  echo "\$ sqe-cli --embedded --memory -e \"... read_csv('data/events.csv') ...\""
  sqe -e "SELECT kind, COUNT(*) AS n, ROUND(SUM(amount),2) AS total FROM read_csv('/data/events.csv') GROUP BY kind ORDER BY total DESC" 2>&1
  echo '```'
  echo
  echo '## Local JSON (read_json) and Parquet (read_parquet)'
  echo '```'
  echo "\$ ... read_json('data/events.json')"
  sqe -e "SELECT COUNT(*) AS rows, ROUND(SUM(amount),2) AS total FROM read_json('/data/events.json')" 2>&1
  echo "\$ ... read_parquet('data/events.parquet')"
  sqe -e "SELECT kind, ROUND(SUM(amount),2) AS total FROM read_parquet('/data/events.parquet') GROUP BY kind ORDER BY kind" 2>&1
  echo '```'
  echo
  echo '## Join two files of different formats in one query'
  echo '```'
  sqe -e "SELECT c.id, c.kind FROM read_csv('/data/events.csv') c JOIN read_parquet('/data/events.parquet') p ON c.id = p.id WHERE c.amount > 10 ORDER BY c.id" 2>&1
  echo '```'
  echo
  echo '## Remote file over HTTPS (read_parquet on a URL)'
  echo '```'
  echo "\$ ... read_parquet('$REMOTE')"
  sqe -e "SELECT COUNT(*) AS rows FROM read_parquet('$REMOTE')" 2>&1
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"
echo
ok "done. Embedded mode leaves nothing behind (ephemeral --memory engine)."
