apiVersion: v1
kind: Service
metadata:
  name: {{ include "sqe.fullname" . }}-coordinator
  labels:
    {{- include "sqe.labels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sqe.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: coordinator
  ports:
    - name: flight-sql
      port: {{ .Values.service.flightSqlPort }}
      targetPort: flight-sql
    - name: trino-http
      port: {{ .Values.service.trinoHttpPort }}
      targetPort: trino-http
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
