#!/usr/bin/env bash
# AWS S3 Tables quickstart: bootstrap a throwaway S3 Tables table bucket with
# CDK, run a create/write/read round-trip through SQE's s3tables backend,
# capture the output, then empty + tear down the bucket.
#
#   ./run.sh             # cdk deploy -> up -> queries -> down -> empty -> cdk destroy
#   ./run.sh --keep      # leave SQE up and the bucket deployed
#   ./run.sh --destroy   # just tear down
#   ./run.sh --check     # same as default, plus assert the key invariants before teardown
#
# Prereqs: Docker, Node + npx, AWS CLI v2, AWS credentials (AWS_PROFILE or
# AWS_* env), and a cdk-bootstrapped account.
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

KEEP=0; DESTROY_ONLY=0; CHECK=0
for a in "$@"; do
  case "$a" in
    --keep) KEEP=1 ;;
    --destroy) DESTROY_ONLY=1 ;;
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --keep, --destroy, or --check)" ;;
  esac
done

require docker aws npx
[ -f .env ] || { [ -f .env.example ] && cp .env.example .env; }
# shellcheck disable=SC1091
[ -f .env ] && { set -a; . ./.env; set +a; }

step "resolving AWS credentials (profile: ${AWS_PROFILE:-default})"
eval "$(aws configure export-credentials --format env 2>/dev/null)" \
  || die "could not resolve AWS credentials. Set AWS_PROFILE or AWS_* env vars."
export AWS_REGION="${AWS_REGION:-$(aws configure get region 2>/dev/null || echo eu-example-1)}"
export CDK_DEFAULT_REGION="$AWS_REGION"
export CDK_DEFAULT_ACCOUNT="$(aws sts get-caller-identity --query Account --output text)"
ok "account $CDK_DEFAULT_ACCOUNT, region $AWS_REGION"

destroy() {
  step "tearing down"
  docker compose down -v 2>/dev/null || true
  # S3 Tables won't delete a non-empty table bucket, so drop the SQE-created
  # table + namespace first (idempotent; ignore if already gone).
  if [ -f cdk-outputs.json ]; then
    ARN=$(python3 -c "import json;print(json.load(open('cdk-outputs.json'))['SqeS3TablesQuickstart']['TableBucketArn'])" 2>/dev/null || true)
    if [ -n "${ARN:-}" ]; then
      aws s3tables delete-table --table-bucket-arn "$ARN" --namespace demo --name events --region "$AWS_REGION" 2>/dev/null && ok "deleted table demo.events" || true
      aws s3tables delete-namespace --table-bucket-arn "$ARN" --namespace demo --region "$AWS_REGION" 2>/dev/null && ok "deleted namespace demo" || true
    fi
  fi
  ( cd cdk && [ -d node_modules ] && npx cdk destroy --force 2>&1 | tail -3 ) || warn "cdk destroy: check the stack manually"
  rm -f sqe.toml.local cdk-outputs.json
  ok "torn down"
}
if [ "$DESTROY_ONLY" -eq 1 ]; then destroy; exit 0; fi

step "cdk deploy (S3 Tables table bucket)"
( cd cdk && { [ -d node_modules ] || npm install --silent; } \
  && npx cdk deploy --require-approval never --outputs-file ../cdk-outputs.json 2>&1 | tail -5 )

ARN=$(python3 -c "import json;print(json.load(open('cdk-outputs.json'))['SqeS3TablesQuickstart']['TableBucketArn'])")
ok "table bucket $ARN"

step "generating sqe.toml.local"
sed -e "s#__TABLE_BUCKET_ARN__#$ARN#g" -e "s#__REGION__#$AWS_REGION#g" sqe.toml > sqe.toml.local

step "starting SQE (s3tables backend)"
docker compose up -d --wait
ok "sqe healthy"

OUT=OUTPUT.md
step "running create/write/read round-trip, capturing to $OUT"
# `|| true` so a failing query (--stop-on-error returns non-zero) does not abort
# the script under `set -e` -- we still want to capture the output, assert on it,
# and tear the stack down rather than leak it.
QUERY_OUT="$(docker compose exec -T -e SQE_PASSWORD=anonymous sqe \
  sqe-cli --port 50051 --user anonymous --file /queries.sql --stop-on-error 2>&1 || true)"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ) against AWS S3 Tables._"
  echo
  echo '## anonymous user, s3tables backend: CREATE TABLE + INSERT + aggregate'
  echo
  echo '`sqe-cli --user anonymous --file queries.sql` over Flight SQL:'
  echo '```'
  echo "$QUERY_OUT"
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

if [ "$KEEP" -eq 1 ]; then
  echo; ok "left running (--keep). Tear down with: ./run.sh --destroy"
  exit 0
fi

if [ "$CHECK" -eq 1 ]; then
  step "checking invariants (reusing the captured queries.sql output)"
  # OUTPUT.md shows the aggregate over the round-trip: purchase -> 55.25, click
  # -> 2.25, and no engine error. The DDL lines emit (0 rows), so assert on the
  # row-value markers, never assert_not_empty.
  assert_contains     "s3tables aggregate shows purchase total" "$QUERY_OUT" "55.25"
  assert_contains     "s3tables aggregate shows click total"    "$QUERY_OUT" "2.25"
  assert_contains     "s3tables aggregate shows purchase row"   "$QUERY_OUT" "purchase"
  assert_not_contains "s3tables run has no error"               "$QUERY_OUT" "error"
  # Tear down before check_summary: check_summary dies on a failed assertion, so
  # summarizing first would leak the deployed S3 Tables bucket.
  destroy
  check_summary
  exit 0
fi
destroy
