#!/usr/bin/env bash
# Bring up Unity Catalog OSS + SQE, browse the catalog over Iceberg REST, and
# capture the output. Unity OSS's Iceberg REST is read-only, so this is a
# metadata/browse demo (see README).
#
#   ./run.sh
#   ./run.sh --down
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

for a in "$@"; do
  case "$a" in
    --down) require docker; step "tearing down"; docker compose down -v; ok "done"; exit 0 ;;
    *) die "unknown arg: $a (use --down)" ;;
  esac
done

require docker
[ -f .env ] || { step "creating .env from .env.example"; cp .env.example .env; }
# shellcheck disable=SC1091
set -a; . ./.env; set +a

step "bringing the stack up"
docker compose up -d --wait
ok "unity + sqe healthy"

OUT=OUTPUT.md
step "browsing the Unity catalog via SQE, capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## SQE browsing Unity Catalog OSS over Iceberg REST'
  echo
  echo '`sqe-cli --user anonymous --file queries.sql`:'
  echo '```'
  docker compose exec -T -e SQE_PASSWORD=x sqe \
    sqe-cli --port 50051 --user anonymous --file /queries.sql 2>&1
  echo '```'
  echo
  echo '## Read attempt: Unity OSS does not serve the bundled table for SELECT'
  echo '```'
  echo '$ sqe-cli -e "SELECT * FROM unity.default.marksheet_uniform LIMIT 3"'
  docker compose exec -T -e SQE_PASSWORD=x sqe \
    sqe-cli --port 50051 --user anonymous -e "SELECT * FROM unity.default.marksheet_uniform LIMIT 3" 2>&1 | head -3 || true
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"
echo
ok "done. Unity API http://localhost:${UNITY_PORT:-18181}, Flight grpc://localhost:${SQE_FLIGHT_PORT:-60051}. Tear down: ./run.sh --down"
