#!/usr/bin/env bash
# Bring up SQE (Nessie catalog) + VictoriaMetrics + Grafana, run some queries to
# generate metrics, then prove SQE's Prometheus metrics are being scraped.
#
#   ./run.sh             # up -> queries -> assert metrics scraped -> capture
#   ./run.sh --down      # tear everything down
#   ./run.sh --check     # up -> queries -> assert metrics scraped (exit code)
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

CHECK=0
for a in "$@"; do
  case "$a" in
    --down) require docker; step "tearing down"; docker compose down -v; ok "done"; exit 0 ;;
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --down or --check)" ;;
  esac
done

require docker curl
[ -f .env ] || { [ -f .env.example ] && cp .env.example .env; }
# shellcheck disable=SC1091
[ -f .env ] && { set -a; . ./.env; set +a; }
VM="http://localhost:${VM_PORT:-18428}"
GRAFANA="http://localhost:${GRAFANA_PORT:-13000}"

step "bringing the stack up (sqe, nessie, rustfs, victoriametrics, grafana)"
docker compose up -d --wait
ok "all services up"

step "generating metrics: running queries.sql a few times"
for _ in 1 2 3; do
  docker compose exec -T -e SQE_PASSWORD=anonymous sqe \
    sqe-cli --port 50051 --user anonymous --file /queries.sql --stop-on-error >/dev/null 2>&1 || true
done
ok "ran queries"

# Give VictoriaMetrics time to scrape SQE's /metrics. Poll on a real SQE metric
# (rows returned by the queries above) so we only proceed once the end-to-end
# pipeline -- sqe -> victoriametrics -- has actually delivered a sample.
wait_http "$VM/api/v1/query?query=up" 2xx 30 "victoriametrics" || true
for _ in $(seq 1 15); do
  hit=$(curl -s "$VM/api/v1/query?query=sqe_rows_returned_total" 2>/dev/null | grep -c '"value"' || echo 0)
  [ "$hit" != "0" ] && break
  sleep 3 2>/dev/null || true
done

OUT=OUTPUT.md
step "capturing scraped SQE metrics to $OUT"
q() { curl -s "$VM/api/v1/query?query=$1" 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); r=d.get('data',{}).get('result',[]); print(r[0]['value'][1] if r else 'no-data')" 2>/dev/null || echo "n/a"; }
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## VictoriaMetrics is scraping the SQE coordinator'
  echo '```'
  echo "scrape target up{job=\"sqe-coordinator\"} = $(q 'up%7Bjob%3D%22sqe-coordinator%22%7D')"
  echo "sqe_rows_returned_total                    = $(q 'sqe_rows_returned_total')"
  echo "sqe_active_sessions                        = $(q 'sqe_active_sessions')"
  echo "sqe_cache_misses_total                     = $(q 'sqe_cache_misses_total')"
  echo "sqe_coordinator_memory_used_bytes          = $(q 'sqe_coordinator_memory_used_bytes')"
  echo '```'
  echo
  echo '## A sample of SQE'"'"'s raw /metrics (sqe_*)'
  echo '```'
  docker compose exec -T sqe sh -lc "curl -s http://localhost:9090/metrics | grep -E '^sqe_(rows_returned_total|active_sessions|cache_(hits|misses)_total|s3_(requests_total|bytes_read_total)|coordinator_memory_used_bytes|files_pruned_minmax_total) '" 2>&1
  echo '```'
  echo
  echo "Grafana (admin/admin): $GRAFANA  -- the provisioned \"SQE Overview\" dashboard"
} | tee "$OUT"
ok "captured to $OUT"

if [ "$CHECK" -eq 1 ]; then
  step "checking invariants (SQE raw /metrics + VictoriaMetrics scrape target)"

  # Load-bearing: SQE's own /metrics endpoint exposes the sqe_* family. This is
  # reliable the moment the coordinator is up. sqe_rows_returned_total is the
  # metric the demo queries above increment (see OUTPUT.md).
  raw_out=$(docker compose exec -T sqe sh -lc "curl -s http://localhost:9090/metrics | grep -E '^sqe_'" 2>&1)
  assert_not_empty "SQE exposes sqe_* metrics"          "$raw_out"
  assert_contains  "raw /metrics has sqe_rows_returned_total" "$raw_out" "sqe_rows_returned_total"
  assert_contains  "raw /metrics has sqe_active_sessions"     "$raw_out" "sqe_active_sessions"

  # End-to-end proof: VictoriaMetrics has scraped the coordinator (up == 1). The
  # poll above already waited for the sample; treat this as a softer end-to-end
  # confirmation alongside the load-bearing raw check.
  up_out=$(q 'up%7Bjob%3D%22sqe-coordinator%22%7D')
  assert_contains "VictoriaMetrics scrapes sqe-coordinator (up=1)" "$up_out" "1"

  check_summary
  exit 0
fi

echo
ok "done. Grafana $GRAFANA, VictoriaMetrics $VM. Tear down: ./run.sh --down"
