#!/usr/bin/env bash
# Set up the Nessie stack, run the demo queries as the anonymous user, and
# capture the output.
#
#   ./run.sh             # up -> queries -> capture
#   ./run.sh --down      # tear everything down
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

for a in "$@"; do
  case "$a" in
    --down) require docker; step "tearing down"; docker compose down -v; ok "done"; exit 0 ;;
    *) die "unknown arg: $a (use --down)" ;;
  esac
done

require docker curl
[ -f .env ] || { step "creating .env from .env.example"; cp .env.example .env; }
# shellcheck disable=SC1091
set -a; . ./.env; set +a

step "bringing the stack up (build SQE on first run; this can take a few minutes)"
docker compose up -d --wait
ok "all services healthy (rustfs, nessie, sqe)"

OUT=OUTPUT.md
step "running demo queries as the anonymous user, capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## anonymous user against Nessie (CREATE SCHEMA + table + read)'
  echo
  echo '`sqe-cli --user anonymous --file queries.sql` over Flight SQL:'
  echo '```'
  docker compose exec -T -e SQE_PASSWORD=anonymous sqe \
    sqe-cli --port 50051 --user anonymous --file /queries.sql --stop-on-error 2>&1
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

echo
ok "done. Flight grpc://localhost:${SQE_FLIGHT_PORT:-60051}, Nessie http://localhost:${NESSIE_PORT:-19120}/api/v2/config. Tear down: ./run.sh --down"
