#!/usr/bin/env bash
# Set up the stack, run the demo queries as two different users, and capture
# the output into OUTPUT.md as committed evidence.
#
#   ./run.sh             # up -> bootstrap -> queries -> capture -> leave running
#   ./run.sh --down      # tear everything down (compose down -v)
#   ./run.sh --with-tests # also run the gated cargo Keycloak tests (needs Rust)
#
# Re-run any time to re-validate from the current state. Use --down then ./run.sh
# for a truly clean run.
set -euo pipefail
cd "$(dirname "$0")"
. ../_shared/lib.sh

WITH_TESTS=0
CHECK=0
for a in "$@"; do
  case "$a" in
    --down) require docker; step "tearing down"; docker compose down -v; ok "done"; exit 0 ;;
    --with-tests) WITH_TESTS=1 ;;
    --check) CHECK=1 ;;
    *) die "unknown arg: $a (use --down, --with-tests or --check)" ;;
  esac
done

require docker curl
[ -f .env ] || { step "creating .env from .env.example"; cp .env.example .env; }
# shellcheck disable=SC1091
set -a; . ./.env; set +a

step "bringing the stack up (build SQE on first run; this can take a few minutes)"
docker compose up -d --wait
ok "all services healthy (keycloak, rustfs, polaris, sqe) and bootstrap completed"

OUT=OUTPUT.md
step "running demo queries, capturing to $OUT"
{
  echo "# Captured output"
  echo
  echo "_Generated by \`./run.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  echo '## adminuser (catalog_admin + data_writer + table_reader)'
  echo
  echo '`sqe-cli --user adminuser --file queries.sql` over Flight SQL:'
  echo
  echo '```'
  docker compose exec -T -e SQE_PASSWORD=adminuser123 sqe \
    sqe-cli --port 50051 --user adminuser --file /queries.sql --stop-on-error 2>&1
  echo '```'
  echo
  echo '## testuser (table_reader only): read is allowed'
  echo
  echo '```'
  docker compose exec -T -e SQE_PASSWORD=testuser123 sqe \
    sqe-cli --port 50051 --user testuser \
    -e "SELECT kind, COUNT(*) AS n FROM quickstart.demo.events GROUP BY kind ORDER BY kind" 2>&1
  echo '```'
} | tee "$OUT"
ok "captured to $OUT"

if [ "$CHECK" -eq 1 ]; then
  step "checking invariants (reusing the two sqe-cli Flight SQL invocations)"

  # adminuser: full create/write/read path via --file. The output mixes the
  # SHOW SCHEMAS result, three (0 rows) lines from DROP/CREATE/INSERT, and the
  # final aggregate -- so we assert on specific markers, not non-emptiness.
  admin_out=$(docker compose exec -T -e SQE_PASSWORD=adminuser123 sqe \
    sqe-cli --port 50051 --user adminuser --file /queries.sql --stop-on-error 2>&1)
  assert_contains    "adminuser sees the demo schema"        "$admin_out" "demo"
  assert_contains    "adminuser reads the purchase total"    "$admin_out" "55.25"
  assert_not_contains "adminuser run has no error"           "$admin_out" "error"

  # testuser (table_reader only): the lower-privileged identity still reads the
  # table adminuser wrote. Bare SELECT, so non-emptiness is a safe check here.
  testuser_out=$(docker compose exec -T -e SQE_PASSWORD=testuser123 sqe \
    sqe-cli --port 50051 --user testuser \
    -e "SELECT kind, COUNT(*) AS n FROM quickstart.demo.events GROUP BY kind ORDER BY kind" 2>&1)
  assert_not_empty   "testuser reads the events table"       "$testuser_out"
  assert_contains    "testuser sees the click + purchase rows" "$testuser_out" "purchase"
  assert_not_contains "testuser run has no error"            "$testuser_out" "error"

  check_summary
  exit 0
fi

if [ "$WITH_TESTS" -eq 1 ]; then
  step "running gated Keycloak integration tests (host, against localhost:${KEYCLOAK_PORT:-28080})"
  require cargo
  SQE_TEST_KEYCLOAK_URL="http://localhost:${KEYCLOAK_PORT:-28080}" \
  SQE_TEST_CLIENT_SECRET="${SQE_CLIENT_SECRET:-sqe-secret-change-me}" \
    cargo test -p sqe-coordinator --test integration_test -- --ignored \
      test_keycloak_auth_with_test_users test_keycloak_token_refresh --nocapture
  ok "Keycloak auth + token-refresh tests passed"
fi

echo
ok "done. Endpoints: Flight grpc://localhost:${SQE_FLIGHT_PORT:-60051}, Trino http://localhost:${SQE_TRINO_PORT:-18080}, Keycloak http://localhost:${KEYCLOAK_PORT:-28080}"
echo "    Tear down with: ./run.sh --down"
