databases:
  trino:
    host: tls-proxy
    port: 8443
    server_address: https://tls-proxy:8443
    jdbc_driver_class: io.trino.jdbc.TrinoDriver
    jdbc_url: jdbc:trino://tls-proxy:8443/iceberg/default?SSL=true&SSLVerification=NONE
    jdbc_user: root
    jdbc_password: s3cr3t
    jdbc_pooling: false

tests:
  assert:
    float_tolerance: 0.000001
